# Generated by Django 4.2b1 on 2023-04-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='masters/images/')),
                ('name', models.TextField()),
                ('specialization', models.TextField()),
                ('link', models.SlugField(unique=True)),
            ],
        ),
    ]
