# Generated by Django 4.2b1 on 2023-04-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='location',
            field=models.CharField(choices=[('1', 'Шишкина'), ('2', 'Заречная')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
