# Generated by Django 4.2b1 on 2023-04-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_alter_master_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='link',
            field=models.URLField(),
        ),
    ]
