# Generated by Django 4.2b1 on 2023-04-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_alter_master_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='master',
            options={'verbose_name': 'Мастера', 'verbose_name_plural': 'Мастера'},
        ),
        migrations.AlterField(
            model_name='master',
            name='link',
            field=models.URLField(verbose_name='Ссылка на мастера'),
        ),
        migrations.AlterField(
            model_name='master',
            name='location',
            field=models.CharField(choices=[('1', 'Шишкина'), ('2', 'Заречная')], max_length=1, verbose_name='Выберите место работы мастера'),
        ),
        migrations.AlterField(
            model_name='master',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Введите имя мастера'),
        ),
        migrations.AlterField(
            model_name='master',
            name='photo',
            field=models.ImageField(upload_to='masters/images/', verbose_name='Выберите изображение'),
        ),
        migrations.AlterField(
            model_name='master',
            name='specialization',
            field=models.TextField(verbose_name='Введите направление деятельности мастера'),
        ),
    ]
