# Generated by Django 4.2b1 on 2023-04-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0004_alter_discount_options_alter_discount_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='image',
            field=models.ImageField(help_text='Картинка должна быть ш.840px на в.720px', upload_to='discount/images/', verbose_name='Выберите изображение'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
    ]
