# Generated by Django 4.2b1 on 2023-04-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicec',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AddField(
            model_name='servicec',
            name='work_type',
            field=models.CharField(choices=[('1', 'Волосы'), ('2', 'Ногти'), ('3', 'Брови/ресницы')], default='Волосы', max_length=1),
            preserve_default=False,
        ),
    ]
