# Generated by Django 4.2b1 on 2023-04-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_servicec_options_servicec_work_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicec',
            options={'verbose_name': 'Услугу', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterField(
            model_name='servicec',
            name='description',
            field=models.TextField(verbose_name='Введите описание услуги'),
        ),
        migrations.AlterField(
            model_name='servicec',
            name='price',
            field=models.CharField(max_length=100, verbose_name='Введите стоимость услуги'),
        ),
        migrations.AlterField(
            model_name='servicec',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Введите название услуги'),
        ),
        migrations.AlterField(
            model_name='servicec',
            name='work_type',
            field=models.CharField(choices=[('1', 'Волосы'), ('2', 'Ногти'), ('3', 'Брови/ресницы')], max_length=1, verbose_name='Выберите тип услуги'),
        ),
    ]
