# Generated by Django 4.2b1 on 2023-04-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_servicec_options_alter_servicec_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicec',
            name='price',
        ),
        migrations.AlterField(
            model_name='servicec',
            name='work_type',
            field=models.CharField(blank=True, choices=[('1', 'Волосы'), ('2', 'Ногти'), ('3', 'Брови/ресницы')], max_length=1, verbose_name='Выберите тип услуги'),
        ),
    ]
