# Generated by Django 4.2b1 on 2023-04-22 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('additional', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photos',
            options={'verbose_name': 'Фотография', 'verbose_name_plural': 'Фотографии работ'},
        ),
    ]
