# Generated by Django 4.2b1 on 2023-04-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional', '0002_alter_photos_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photos',
            options={'verbose_name': 'Фотографию', 'verbose_name_plural': 'Фотографии работ'},
        ),
        migrations.AlterField(
            model_name='photos',
            name='image',
            field=models.ImageField(upload_to='additional/images/', verbose_name='Выберите фотографию'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Введите заголовок'),
        ),
    ]
